### PR TITLE
Added MeeBlip geode, Fred's Lab Buzzzy!

### PR DESCRIPTION
**Pull request by fauxstor**

### CODE REVIEW

**Comment by benjaminfox** [comment]
Great PR, thanks a lot! Just so you know, right now the `cc_min_value` and `cc_max_value` need to be just integers like `0` instead of `0-63` - your format is better and more readable but not yet ingestible by our client.

**Comment by fauxstor** [comment]
I can add to the notes that the switches are binary with the low and high ranges acting as ON or OFF.

**Comment by benjaminfox** [comment]
Great 😎Just need the column values themselves to be 0 or 127. I'd never heard of these devices btw, very cool. You post your music anywhere?

**Comment by benjaminfox** [comment]
*need the column values to be integers BETWEEN 0 and 127 rather.

**Comment by fauxstor** [comment]
NM, you already did.  Thanks!

**Comment by fauxstor** [comment]
> Great 😎Just need the column values themselves to be 0 or 127. I'd never heard of these devices btw, very cool. You post your music anywhere?

Nothing yet using these little monsters.  I'll let you know, though!

**Pull request merged**
